apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base-openjdk16
  name: base-openjdk16
  namespace: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-openjdk16
  template:
    metadata:
      labels:
        app: base-openjdk16
    spec:
      containers:
      - image: emreodabas/hello-app-spring-boot:base-openjdk16
        name: hello-app-spring-boot
        resources:
          requests:
            memory: "2Gi" 
            cpu: "1000m"  
          limits:
            memory: "2Gi"
            cpu: "1000m" 

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: base-openjdk16
  name: base-openjdk16
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: base-openjdk16
  type: NodePort
status:
  loadBalancer: {}
